language: python

services:
  - docker

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker-compose --version

jobs:
 include:
   - stage: docker build image
   - script:
     - echo "building $IMAGE_NAME image"
     - docker image build -t amenezes/$IMAGE_NAME:$IMAGE_TAG .
     - docker image push amenezes/$IMAGE_NAME:$IMAGE_TAG
   - script:
     - echo "building latest image"
     - docker image build -t amenezes/$IMAGE_NAME: .
     - docker image push amenezes/$IMAGE_NAME:
env:
  global:
   - IMAGE_TAG=stable
   - IMAGE_NAME=ansible
